---

#  - name: backup db
    #become: true
    #become_user: root
    #     shell: mysqldump -u root --single-transaction --all-databases  > /home/all.sql
    #  tags:
    #   - backup

- name: backup galera cluster
  mysql_db:
    state: dump
    name: all
    target: "{{ path_backup }}all.sql"
  tags:
    - backup



- name: scp backup to server
  fetch:
    src: "{{ path_backup }}all.sql"
    dest: "{{ backup_storage_path }}all.sql"
    flat: yes
    validate_checksum: no
  tags:
    - backup



- name: restart mariadb
  service: name=mysql enabled=yes state=restarted
  tags:
    - mysql_restart

