---
- name: gather variable container lxc galera cluster
  shell: lx c-ls -f |grep galera |cut -d " " -f 1 
  register: lxc_info
  tags:
     - galera 


- name: gather variable controller name1
  shell: lxc-ls -f |grep galera |cut -d " " -f 1 |cut -b 1-6
  register: controller_name
  tags:
    - galera


- name: lxc stop
  shell: lxc-s top -n "{{ lxc_info.stdout }}"
  tags:
     - galera 

      
- name: lxc destroy
  shell: lxc-destroy -n "{{ lxc_info.stdout }}"
  tags:
     - galera


- name: remove file lxc container galera cluster
  shell:  " rm -rf /openstack/{{ lxc_info.stdout }}/*"
  tags:
    - galera


- name: run setup-hosts
  shell: "{{ setup_hosts }} -l {{ controller_name.stdout }} -l {{ lxc_info.stdout }}"
  tags:
    - galera


- name: run setup-infrastructure
  shell: " {{ setup_infrastructure }} --limit {{ lxc_info.stdout }} "
  tags:
    - galera

#======================================debug==============================================================

- name: gather variable container lxc galera cluster
  shell: lxc-ls -f  |grep galera |cut -d " " -f 1 
  register: lxc_info
  tags:
     - debug  


- name: gather variable controller name1
  shell: lxc-ls -f |grep galera |cut -d " " -f 1 |cut -b 1-6
  register: controller_name
  tags:
    - debug 



- name: lxc stop
  debug:  
    msg: "lxc-stop -n {{ lxc_info.stdout }}"
  tags:
     - debug  

      
- name: lxc destroy
  debug:  
    msg: "lxc-destroy -n {{ lxc_info.stdout }}"
  tags:
     - debug  


- name: remove file lxc container galera cluster
  debug: 
    msg: " rm -rf /openstack/{{ lxc_info.stdout }}/*"
  tags:
    - debug   


- name: run setup-hosts
  debug:  
    msg: "{{ setup_hosts }} -l {{ controller_name.stdout }} -l {{ lxc_info.stdout }}"
  tags:
    - debug  


- name: run setup-infrastructure
  debug:   
    msg: " {{ setup_infrastructure }} --limit {{ lxc_info.stdout }} "
  tags:
    - debug
