---
- name: Restor multiple databases
  mysql_db:
    state: import
    name: "{{ item }}"  
    target: "{{ path_backup }}{{ item }}.sql"
  with_items: "{{ db_names }}"
  tags:
    - resotor_one_by_one

- name: Restor nova databases
  mysql_db:
    state: import
    name:
      - nova
      - nova_api
      - nova_cell0  
    target: "{{ path_backup }}nova_all.sql"
  tags:
    - nova

- name: Restor cinder databases
  mysql_db:
    state: import
    name: cinder 
    target: "{{ path_backup }}cinder.sql"
  tags:
    - cinder

- name: Restor keystone databases
  mysql_db:
    state: import
    name: keystone
    target: "{{ path_backup }}keystone.sql"
  tags:
    - keystone

- name: Restor neutron databases
  mysql_db:
    state: import
    name: neutron 
    target: "{{ path_backup }}neutron.sql"
  tags:
    - neutron

- name: Restor placement databases
  mysql_db:
    state: import
    name: placement 
    target: "{{ path_backup }}placement.sql"
  tags:
    - placement


- name: Restor rally databases
  mysql_db:
    state: import
    name: rally 
    target: "{{ path_backup }}rally.sql"
  tags:
    - rally










- name: debug
  debug:
    msg: "{{ item }}"
  with_items: "{{ db_names }}"
  tags:
    - test



