---
# defaults file for mysql_backup
project_name: "backup galera cluster"
path_backup: /home/
name_backup_file_infra1: backup_galera_infra1
name_backup_file_infra2: backup_galera_infra2
name_backup_file_infra3: backup_galera_infra3
date: "{{ 'date +%Y%m%d-%H%M' }}"
db_names:
  - cinder
  - keystone
  - neutron
  - nova
  - nova_api
  - nova_cell0
  - placement
  - rally
  - glance

infra1_galera: "infra1_galera_container-5b11d5be"
infra2_galera: "infra2_galera_container-b8b8ea27"
infra3_galera: "infra3_galera_container-b74ad98e"
infra_galera:
  infra1: "infra1_galera_container-5b11d5be"
  infra2: "infra2_galera_container-b8b8ea27"
  infra3: "infra3_galera_container-b74ad98e"

setup_hosts: "openstack-ansible /opt/openstack-ansible/playbooks/setup-hosts.yml"

setup_infrastructure: "openstack-ansible /opt/openstack-ansible/playbooks/setup-infrastructure.yml"
