---
- name: Dump multiple databases
  mysql_db:
    state: dump
    name: "{{ item }}"  
    target: "{{ path_backup }}{{ item }}.sql"
    login_user: root
    login_password: ""
  with_items: "{{ db_names }}"
  tags:
    - backup_one_by_one


### backup nova db "
- name: nova backup
  mysql_db:
    state: dump
    name:
      - nova
      - nova_api
      - nova_cell0
    target: "{{ path_backup }}nova_all.sql"
    login_user: root
    login_password: ""
  tags:
    - nova

### backup cinder db "
- name: cinder backup
  mysql_db:
    state: dump
    name: cinder
    target: "{{ path_backup }}cinder.sql"
    login_user: root
    login_password: ""
  tags:
    - cinder


### backup keystone db "
- name: keystone backup
  mysql_db:
    state: dump
    name: keystone
    target: "{{ path_backup }}keystone.sql"
    login_user: root
    login_password: ""
  tags:
    - keystone

### backup neutron db "
- name: neutron backup
  mysql_db:
    state: dump
    name: neutron
    target: "{{ path_backup }}neutron.sql"
    login_user: root
    login_password: ""
  tags:
    - neutron


### backup placement db "
- name: placement backup
  mysql_db:
    state: dump
    name: placement
    target: "{{ path_backup }}placement.sql"
    login_user: root
    login_password: ""
  tags:
    - placement 


### backup rally db "
- name: rally backup
  mysql_db:
    state: dump
    name: rally
    target: "{{ path_backup }}placement.sql"
    login_user: root
    login_password: ""
  tags:
    - rally 



## check ansible

- name: debug
  debug:
    msg: "{{ item }}"
  with_items: "{{ db_names }}"
  tags:
    - test
