---
- name: Restor multiple databases
  mysql_db:
    state: import
    name: "{{ item }}"  
    target: "{{ path_backup }}{{ item }}.sql"
  with_items: "{{ db_names }}"
  tags:
    - resotor_one_by_one

- name: debug
  debug:
    msg: "{{ item }}"
  with_items: "{{ db_names }}"
  tags:
    - test



