---
#- name: gather variable container lxc galera cluster
#  shell: cat /etc/hosts |grep galera |cut -d " " -f 3
#  register: lxc_info
#  tags:
#    - galera 


#- name: gather variable controller name
#  shell: cat /etc/hosts |grep galera |cut -d " " -f 2 |cut -b 1-6
#  register: controller_name
#  tags:
#    - galera
   

#- name: debugin code
#  debug:
#    msg: "{{ setup_hosts }} -l {{ controller_name.stdout[0] }} -l {{ lxc_info.stdout }}"
#  tags:
#    - galera

- name: run setup-hosts
  shell : " {{ setup_hosts }} -l  {{ inventory_hostname }} -l {{ infra_galera.{{ inventory_hostname }} }}"
  tags:
     - galera_infra
 
#- name: run setup-hosts
#  shell : " {{ setup_hosts }} -l infra2 -l {{ infra2_galera }}"
#  tags:
#     - galera_infra2
 
 
#- name: run setup-hosts
#  shell : " {{ setup_hosts }} -l  infra3 -l {{ infra3_galera }}"
#  tags:
#    - galera_infra3
 
- name: run setup-infrastructure
  shell:  " {{ setup_infrastructure }} --limit {{ infra_galera.{{ inventory_hostname }} }}"
  tags:
    - galera_infra 

 
#- name: run setup-infrastructure
#  shell:  " {{ setup_infrastructure }} --limit {{ infra2_galera }}"
#  tags:
#    - galera_infra2


 
##- name: run setup-infrastructure
#  shell:  " {{ setup_infrastructure }} --limit {{ infra3_galera }}"
#  tags:
#    - galera_infra3



