---
# defaults file for mysql_backup
project_name: "backup galera cluster"
ip_infra1_galera: 172.16.105.96
ip_infra2_galera: 172.16.105.97 
ip_infra2_galera: 172.16.105.157
path_backup: /home/
name_backup_file_infra1: backup_galera_infra1
name_backup_file_infra2: backup_galera_infra2
name_backup_file_infra3: backup_galera_infra3

db_names:
  - cinder
  - keystone
  - neutron
  - nova
  - nova_api
  - nova_cell0
  - placement
  - rally
  - glance

