- name: Restore All Database 
  mysql_db:
    state: import      
    name: all 
    target: "{{ path_backup }}all.sql"
  tags:
    - restore


#- name: Restore database
#  tasks:
#    - shell: mysql -u root  < "{{ path_backup }}all.sql"
#  tags:
#    - restore


